[package]
name = "keyslate"
description = "A fully local, keyboard-first note-taking app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
keyslate-core = { path = "../crates/keyslate-core" }
notify-debouncer-mini = "0.7.0"
serde_json = { workspace = true }
tauri = { version = "2.12.1", features = [] }
tauri-plugin-dialog = "2.8.1"
tauri-plugin-global-shortcut = "2.4.0"
